# Generated by Django 3.1.3 on 2020-11-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='sub_categories',
            new_name='sub_category',
        ),
    ]
