# Generated by Django 3.1.3 on 2020-11-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201120_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubProduct',
            new_name='AdditionalProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_product',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_products',
            field=models.ManyToManyField(related_name='_product_additional_products_+', through='product.AdditionalProduct', to='product.Product'),
        ),
        migrations.AlterModelTable(
            name='additionalproduct',
            table='additional_products',
        ),
    ]
