# Generated by Django 3.1.3 on 2020-11-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201120_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='option',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='product.productdetail'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='sub_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='product.productdetail'),
        ),
        migrations.AlterField(
            model_name='review',
            name='afforability',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='delivery',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='durability',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.CreateModel(
            name='ColorSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(through='product.ColorSet', to='product.Color'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size'),
        ),
    ]
