# Generated by Django 3.1.3 on 2020-11-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201122_0029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='color',
            table='colors',
        ),
        migrations.AlterModelTable(
            name='productdetail',
            table='product_details',
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
    ]
