# Generated by Django 3.1.3 on 2020-11-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201123_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='afforability',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='delivery',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='durability',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
