# Generated by Django 3.1.3 on 2020-11-24 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201124_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='color',
        ),
        migrations.CreateModel(
            name='ColorSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(through='product.ColorSet', to='product.Color'),
        ),
    ]
