# Generated by Django 3.1.3 on 2020-11-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201118_1544'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posttag',
            table='post_tags',
        ),
    ]
