# Generated by Django 3.1.3 on 2020-11-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201122_0033'),
        ('post', '0003_auto_20201121_1718'),
    ]

    operations = [
    ]
