# Generated by Django 3.1.3 on 2020-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201118_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
