# Generated by Django 3.1.3 on 2020-11-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201120_1750'),
        ('user', '0004_auto_20201118_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'collection_bookmarks',
            },
        ),
    ]
