# Generated by Django 3.1.3 on 2020-11-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201124_1732'),
        ('product', '0011_auto_20201124_1310'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.status'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipment',
            field=models.CharField(default='쿠팜', max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tracking_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CartBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'cart_boxs',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='cartbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.cartbox'),
            preserve_default=False,
        ),
    ]
