# Generated by Django 3.1.3 on 2020-11-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201124_0952'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
