# Generated by Django 3.1.3 on 2020-11-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201124_1310'),
        ('order', '0003_remove_cartbox_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbox',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
