# Generated by Django 3.1.3 on 2020-11-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201126_1930'),
        ('order', '0005_cart_color'),
    ]

    operations = [
    ]
